# Generated by Django 5.1.2 on 2024-11-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
    ]
