# Generated by Django 5.1.2 on 2024-11-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_add_qualification_field'),
        ('home_page', '0002_auto_20241129_0123'),
    ]

    operations = [
    ]
