# Generated by Django 5.1.2 on 2024-11-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_merge_20241129_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='preferred_mentorship_format',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_mentorship_format',
            field=models.TextField(blank=True, null=True),
        ),
    ]
